### ISSUE TITLE
3Dmigoto F6 toggling mods causes characters to glitch out in game for some people 

### ISSUE THREAD

**Issue by Jorixon** [Jorixon/JASM#101]
Issue reported in AGMG discord

>pressing F6 to temporarily disable mods in 3Dmigoto now inexplicably causes all characters to turn into polygonal horrors the same way they do when loading multiple mods on the same character/loading outdated mods.

Can't replicate it myself. ShaderFixes problem perhaps?

**Comment by Trackerlist** [comment]
Afaik, just press F10 when this happens and it will be fixed.
