### ISSUE TITLE
[Request] Better way to switch between GI and SR 

### ISSUE THREAD

**Issue by kanonmelodis** [Jorixon/JASM#113]
I played both GI and SR. Whenever I want to open the other, I have to open the settings then switch and restart (BTW, the program frequently fails to restart automatically). I need a more convenient UI and It would be best without restarting.

**Comment by Jorixon** [comment]
HI,
I've changed the code that is used to restart the app in this release. Hopefully it's bit more reliable now.

I know it's a bit cumbersome having to navigate into the settings will probably change it at some point. But changing without restarting is quite cumbersome from a code perspective so unlikely to change in the near future atleast.
