### ISSUE TITLE
JASM update for star rail 2.0/2.1 (Question + Idea)

### ISSUE THREAD

**Issue by DraGZ76** [Jorixon/JASM#131]
New characters were added

So I ask for an update and have them added without worrying for future

Links are to transparent PNG's which were taken from [HoneyHunter Website](https://hsr.honeyhunterworld.com/?lang=EN)

In 2.0 [Black Swan](https://imgur.com/v9d00aS.png) // [Sparkle](https://imgur.com/zjZwSX0.png)

In 2.1 There will be [Acheron](https://imgur.com/ee6DGZgl.png) // [Aventurine](https://imgur.com/bpPgFP5.png) -- 4* [Gallagher](https://imgur.com/MYUkx7A.png)

Or a way to add new characters ourselfes
![image32131231](https://github.com/Jorixon/JASM/assets/82879008/e2f5bb36-c210-4653-9146-61fce6c2dc2e)

**Comment by Jorixon** [comment]
I've had this feature in the back of my mind when working and I've laid the groundwork for it to some extent. #62 
Don't know when I'll add it, but it is planned :)
