### ISSUE TITLE
Fix the submit/changing mods EN/CN version

### ISSUE THREAD

**Issue by mawrand** [Jorixon/JASM#144]
When i try change the mods to CN Version from EN version. it get renamed but not changing the category itself..

same when i trying submit the mods in the exact category. always entry for EN version

![Screenshot 2024-03-15 222832](https://github.com/Jorixon/JASM/assets/111240705/b70c1cd4-4463-4430-88f8-a89a02852f06)

**Comment by Jorixon** [comment]
Thanks for your report!

This should now be fixed in v2.4.0, if the issue still persists then just reopen this issue again
