### ISSUE TITLE
Creating png for preview instead of bitmap

### ISSUE THREAD

**Issue by Akuserureta** [Jorixon/JASM#163]
Hi, Thank you for the great tool, it really helped me alot managing my mods.

Can I suggest to change the way it saved the preview picture? Currently I'm saving my preview by snipping the pic & paste it to the 
blank picture preview & saved it. however it saved into bitmap format instead of PNG, could you please made it to file name as "preview" and PNG file format?

Thank you again

**Comment by Jorixon** [comment]
This should be fixed, there was a bug where it chose the bitmap format over the png format.

If this is still an issue just mention me
