### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by Rafedo75** [Jorixon/JASM#171]
Hi guys 
when i try to open the app nothing happens, not even an error message or a new line in the logs
can you help me please?

**Comment by Avadhut09** [comment]
Yes, this is happening to me now. The app don't even respond, I tried downgrading the version but no results.
This started happening after I put the JASM exe location in QuickModStarter - Auto 3DMigoto Launcher application, after that any version of the app is not responding, even after removing QuickModStarter from my system.

**Comment by Jorixon** [comment]
I belive this is a Windows App Runtime issue #72. I'm unable to recreate this myself. 

I'll do som research and see if I can find any sort of fix for this

**Comment by Jorixon** [comment]
I've modified the build process for JASM, and you can download this modified version [here](https://github.com/Jorixon/JASM/actions/runs/8679201304/artifacts/1412084715) and the [build action](https://github.com/Jorixon/JASM/actions/runs/8679201304). 

This version has all dependencies bundled with it so its size is quite large, but it may solve the problem of it not starting.

**Comment by Avadhut09** [comment]
![image](https://github.com/Jorixon/JASM/assets/69319043/1c51dab7-4ff9-49a3-91cc-372292e9afe2)
I tried the modified build of JASM, I checked the event log and found Windows App Runtime 
   ERROR 0x80070490: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version >= 5001.95.533.0)

**Comment by Avadhut09** [comment]
Here's an update on my situation of JASM not opening up.
It started working!
So I tried uninstalling any previous versions of Windows App Runtime packages that were installed in my system using the powershell and use the above mentioned modified JASM version. As is opened the application it started working.

**Comment by Jorixon** [comment]
Closing this as I belive the self contained version fixes this issue.
