### ISSUE TITLE
ZZZ support?

### ISSUE THREAD

**Issue by K1ssSh0t** [Jorixon/JASM#204]
**Describe the solution you'd like**
Add ZZZ support

**Additional context**
Is a Hoyo game so the implementation should be easy.

**Comment by Pyrageis** [comment]
did this ahead of time, just dont know how to make it select able so if Jorixon could do that I could add the files I prepared in advance and in theory it should be good to go

**Comment by Jorixon** [comment]
> did this ahead of time, the characters images elements game.json and all that just dont know how to make it select able so if Jorixon could do that I could add the files I prepared in advance and in theory it should be good to go

Thanks for the help again Pyrageis. Maintaining these json files is quite a chore.

I've created a draft PR #205 where I changed som stuff and added support for ZZZ. If there is anything else, I can assist with just mention it.
