### ISSUE TITLE
Fixed question about window size

### ISSUE THREAD

**Issue by percy4** [Jorixon/JASM#221]
I'm always frustrated When I use it, I don't like to full screen the whole software, so I window it to my preferred size. But after I reopen this software, the window size automatically changes again, which is very disturbing for me. Finally thanks a lot for your software, it works great!

**Comment by Jorixon** [comment]
Hi
Does this happen when simply closing and reponing the app? One thing I can mention is that the location of the window and size is currently saved separately for each game (which isn't ideal, but it is how it currently works)

**Comment by percy4** [comment]
> Hi 你好 Does this happen when simply closing和reponing the app? One thing I can mention is that the location of the window和size is currently saved separately for each game (which isn't ideal, but it is how it currently works)当简单地关闭并重新启动应用程序时，会发生这种情况吗？我可以提到的一件事是，窗口的位置和大小目前是为每个游戏单独保存的（这并不理想，但这就是它目前的工作方式）

Yes, it happens and it gets bigger and bigger every time I reopen the program. I think it might be because my computer has two screens, one 4k and one 2k. you guys might not have adapted for this situation, hopefully it'll be improved

**Comment by Jorixon** [comment]
In version 2.13.3 I've added the option to disable window size and window positioning saving. This is more of a bandaid fix but hopefully it partially resolves your issue.

**Comment by percy4** [comment]
> In version 2.13.3 I've added the option to disable window size和window positioning saving. This is more of a bandaid fix but hopefully it partially resolves your issue.在版本 2.13.3 中，我添加了禁用窗口大小和窗口位置保存的选项。这更像是一个创可贴修复，但希望它能部分解决您的问题。

Thanks for the quick update. So far I'm doing better after turning off two options. You are a very professional worker.
