### ISSUE TITLE
i

### ISSUE THREAD

**Issue by TinoonH** [Jorixon/JASM#226]
![ee7b07e1126b9fae2e4213d44473f510](https://github.com/user-attachments/assets/b24623c2-5b2a-4fe9-8202-dad4d9b94bff)

will err 

![aa187bc5ebe37069ab042a079d39373a](https://github.com/user-attachments/assets/2d0a240e-8c40-4d3d-ae8e-12fd14e13d8f)
 
so i run cmd ：sfc /scannow 
it still not working

**Comment by Jorixon** [comment]
Does the error happen when you press the Browse button?

**Comment by asdfthorn** [comment]
I encountered the same error.
It happed after updating to the latest microsoft C++ redistributable while installing WWMI from here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by TinoonH** [comment]
yes when i press Browse button . yes 

even i use Administrator privileges

**Comment by TinoonH** [comment]
It's worth mentioning that when I first downloaded JASM it worked fine, maybe I updated net or something, it didn't work at first, and it didn't work to reinstall

**Comment by TinoonH** [comment]
I solved it, I turned off admin mode and he actually worked
