### ISSUE TITLE
Fischl and lynette duplicate id

### ISSUE THREAD

**Issue by monado1110** [Jorixon/JASM#24]
i have two mods, one is fishcl another is lynette but it shows both are fischl mod

![image](https://github.com/Jorixon/JASM/assets/36404361/32af7335-242f-4cfa-a389-a81579dc019a)

**Comment by Jorixon** [comment]
If this happened when it regoranized mods its likley that it recognized the mod as a fischl mod and moved it there. It tries to find a character name in folder name when determening where to move mods. In case you dont know you can right click and manually move the mod to another character. 

I've checked the characters folder and they have different ids so I don't think that the problem.

If this is sill an issue then I'll need more info on how to reproduce it.
