### ISSUE TITLE
Can we add characters ourselves?

### ISSUE THREAD

**Issue by AsukaSoryu0** [Jorixon/JASM#268]
When a new character is released in the version update, can't get the latest character list, can only wait for the software update?

**Comment by AronKTA** [comment]
You can add them by editing a file named "charactere.json" inside the JASM folder
In my case, I tried adding Xilonen and didnt have any problems

This is the file
![Screenshot_2](https://github.com/user-attachments/assets/46f4b99e-8675-4a75-9a89-8e5da9883c09)
("Documentos" means Documents)

You open it, go all the way to the bottom and add this
![Screenshot_1](https://github.com/user-attachments/assets/6c2cab1a-c8c3-4ee4-af32-fc8db9e7d02f)

Then you can add the image that appear in the character overview by downloading the image and putting it in this folder
![Screenshot_3](https://github.com/user-attachments/assets/291b2728-5777-4629-b73d-822494a05e0f)

And thats it, its really easy
Sorry if my english isnt very good, I speak spanish

**Comment by AronKTA** [comment]
In case Xilonen is the one you want to add

you can download the image from here and rename it to "Character_Xilonen_Thumb.png"
https://gensh.honeyhunterworld.com/i_n210300/?lang=ES

And this is what you need to add in the file 

{
    "Keys": [
      "xilonen"
    ],
    "ReleaseDate": "2024-10-09T00:00:00",
    "Image": "Character_Xilonen_Thumb.png",
    "Rarity": 5,
    "Element": "Geo",
    "Class": "Sword",
    "Region": [
      "Natlan"
    ],
    "ModFilesName": "Xilonen",
    "InGameSkins": [],
    "InternalName": "Xilonen",
    "DisplayName": "Xilonen"
   }
]

**Comment by AsukaSoryu0** [comment]
> 如果 Xilonen 是您要添加的
> 
> 您可以从此处下载图像并将其重命名为“Character_Xilonen_Thumb.png”https://gensh.honeyhunterworld.com/i_n210300/?lang=ES
> 
> 这就是您需要在文件中添加的内容
> 
> {“Keys”： [ “xilonen” ]， “ReleaseDate”： “2024-10-09T00：00：00”， “Image”： “Character_Xilonen_Thumb.png”， “Rarity”： 5， “Element”： “Geo”， “Class”： “Sword”， “Region”： [ “Natlan” ]， “ModFilesName”： “Xilonen”， “InGameSkins”： []， “InternalName”： “Xilonen”， “DisplayName”： “Xilonen” } ]

谢谢你的解答！我到现在才看到，抱歉！
