### ISSUE TITLE
Can't disable mods through the app

### ISSUE THREAD

**Issue by nick1167607715** [Jorixon/JASM#277]
**Describe the bug**
I can't Disable/Enable in the app. I have to manually go to the folder and either put "disable_" in the name or remove the mod I don't want active. 
I'm sure it must be something I'm not doing right or that I don't know I should have done. 

**To Reproduce**
1. I just go to the character, try to click to disable it alone or all mods together. 
2. Every time I try it I get a meesage like this:
Access to the path 'C:\Users\<username>\Downloads\Genshin Stonks\3dmigoto\Mods\character\jean\bunnyartoria Jean' is denied.

**Expected behavior**

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/498fdeb5-add9-4db3-adcb-4728a1d827d2)

**Logs**
[log.txt](https://github.com/user-attachments/files/17447608/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22h2

**Additional context**
I'm still new to this so sorry for asking if the answer was obvious. And thanks in advance for anyone who can give me a hand.

**Comment by Pyrageis** [comment]
this isn't a bug, jasm doesnt have the permissions to the folder/files, or one of the files you have open in another program
