### ISSUE TITLE
Keybinds not recognized or automatically populated

### ISSUE THREAD

**Issue by Foolishkun** [Jorixon/JASM#279]
**Describe the bug**
Some mods keybind data is unable to be fetched automatically or at all.

**To Reproduce**

(Unable to be fetched at all)
1. Install https://gamebanana.com/mods/536494
2. Set ini to "Kokomi NSFW.ini"
3. No keybinds are recognized

(Unable to be fetched automatically)
1. Install https://gamebanana.com/mods/550473
2. "Noelle.ini" is not automatically detected
3. Manually set ini to "Noelle.ini"
4. Keybind data populates as expected

**Expected behavior**
After installing it typically automatically detects the keybinds

**Screenshots**
<img width="336" alt="JASM_-_Just_Another_Skin_Manager_oxZ0EAazT2" src="https://github.com/user-attachments/assets/46d959bb-5cba-40f2-97bc-1bd44195d109">

**Logs**
(Unable to be fetched at all)

> [2024-10-30T23:43:13 INF ArchiveService] Extracting 7z archive with command: x "c:\users\x\appdata\local\jasm\applicationdata_genshin\moddownloads\summer_idol_kokomi_nsfw_by_dasbirb_b637e_!!_536494_!!_1274220_!!_9f4f2e223d3cf22fee43f744f769736f.zip" -o"C:\Users\x\AppData\Local\Temp\JASM_TMP\95d7d8f3-04e0-424d-8190-134d79d870e7\summer_idol_kokomi_nsfw_by_dasbirb_b637e_!!_536494_!!_1274220_!!_9f4f2e223d3cf22fee43f744f769736f.zip" -y
> [2024-10-30T23:43:14 INF ArchiveService] 7z extraction finished with exit code 0
> [2024-10-30T23:43:20 INF NotificationManager] Title: Mod 'Summer Idol Kokomi [NSFW]' installed | Body: Mod 'Summer Idol Kokomi [NSFW]' (Summer Idol Kokomi), was successfully added to Sangonomiya Kokomi ModList

(Unable to be fetched automatically)
> [2024-11-01T15:10:24 INF ArchiveService] Extracting 7z archive with command: x "c:\users\x\appdata\local\jasm\applicationdata_genshin\moddownloads\kfc_noelle_dbv_nsfw_by_dasbirb_!!_550473_!!_1305579_!!_7b5c625230e246c2e35e927a7d71292a.zip" -o"C:\Users\x\AppData\Local\Temp\JASM_TMP\00d3af50-1e85-4929-b6a4-14a9cfaec647\kfc_noelle_dbv_nsfw_by_dasbirb_!!_550473_!!_1305579_!!_7b5c625230e246c2e35e927a7d71292a.zip" -y
> [2024-11-01T15:10:24 INF ArchiveService] 7z extraction finished with exit code 0
> [2024-11-01T15:10:32 INF NotificationManager] Title: Mod 'KFC Noelle - DB Edition' installed | Body: Mod 'KFC Noelle - DB Edition' (KFC Noelle dbv), was successfully added to Noelle ModList

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 23H2

**Additional Questions/Information**
When selecting "set mod .ini file" could you make it so it opens the current mods folder? Just a nice QoL for when needing to manually select the ini.

Is their any plan to incorporate the Description field anywhere? Would help for when the keybinds cant be found at all. Also when the mod has more than one ini with keybinds.

**Comment by Jorixon** [comment]
Hi thanks for your detailed report 

Keybind handling and recognition in JASM is currently in a pretty bad state and I have plans to improve/redo it. I want it to be able to handle the cases you mentioned above.

However, as of right now it will only detect the keyswap .ini file automatically, if it is named "Script.ini" OR "merged.ini". This means there are quite a lot of mods where jasm can't automatically detect it. Should probably mention it in the FAQ...

For your other question if the ""set mod .ini file" can open the explorer in the mods folder." It's something I've looked into a few times for another issue #172, (and by being annoyed by it myself lol). As of now I'm currently using a built-in file picker from Microsoft which seems to have a limitation where it opens by default. But other apps are able to to do it somehow, so there is a solution I just need to find out how ;) 

Alternatively, write my own file picker >.<

I've renamed "description" to "note". There is now a column in the grid called notes where the text is displayed. The idea was to use it for small quick notes about mods, as there is no good place to display a large description with the current layout of the app.

**Comment by Foolishkun** [comment]
Ahh so that's what it is, good to know.
Happy to hear you're looking into things!
imo a good place for a larger description box would be on the left side, under the "Select Skin" - I don't believe anything uses that space.
The option you've added to hide/show the "Mod Folder Names" column is good. Any plans to have the option for every other column as well?
