### ISSUE TITLE
Error when drag and dropping.

### ISSUE THREAD

**Issue by GKJU4R7** [Jorixon/JASM#285]
An error pops up when I try to drag and drop a mod into a character's folder. It prompted me to restart the app, but it still happens. This is what also appeared:

System.Runtime.InteropServices.COMException (0x80040064)
   at GIMI_ModManager.WinUI.Views.CharacterDetailsPages.CharacterDetailsPage.ModListArea_OnDragEnter(Object sender, DragEventArgs e) in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\Views\CharacterDetailsPages\CharacterDetailsPage.xaml.cs:line 231
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by kanonmelodis** [comment]
I have met the same problem. It happens when drag&drop from an archive and It works good in v2.16.3 and before.

**Comment by wjxdsg** [comment]
me too its broken

**Comment by Jorixon** [comment]
Tried looking into this today, but I'm unable to reproduce this bug. Do any of you have en example mod or archive this happens to? I also tried downloading a bunch of mods and drag and dropping the archives from file explorer into JASM without any issue.

If you go into settings and ticking this box, does drag and drop work then?
![image](https://github.com/user-attachments/assets/2a5f5c7c-a129-4d9e-b4d0-8e309c30068a)


I noticed drag and drop does not work when running as an Administrator for some reason...

**Comment by kanonmelodis** [comment]
> Tried looking into this today, but I'm unable to reproduce this bug. Do any of you have en example mod or archive this happens to? I also tried downloading a bunch of mods and drag and dropping the archives from file explorer into JASM without any issue.
> 
> If you go into settings and ticking this box, does drag and drop work then? ![image](https://private-user-images.githubusercontent.com/143650598/384688138-2a5f5c7c-a129-4d9e-b4d0-8e309c30068a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDI1MzksIm5iZiI6MTczMTI0MjIzOSwicGF0aCI6Ii8xNDM2NTA1OTgvMzg0Njg4MTM4LTJhNWY1YzdjLWExMjktNGQ5ZS1iNGQwLThlMzA5YzMwMDY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMjM3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzFiN2Y4MTY1MTgzMjZlYzU1OTVlNzNmNjUxNDkzZDczMDliZWY3YmUyNzQ0ZTU1YzNlYjg5NmUxNzE3ZTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fj8X0LCelfFUnROu8eKXJxAlc_PsUPllir1mD-jeKf0)
> 
> I noticed drag and drop does not work when running as an Administrator for some reason...

I think it only occurs when dragging a file(or folder) from an unzip software like 7-zip or winRAR. Dragging a archive file from explorer directly is ok.

**Comment by Jorixon** [comment]
I tried installing and using winrar and i got the error myself. Seems to be WinRAR specific? I personally use 7zip and haven't experienced this isse.

PR #288 has a potential specific fix for the winrar issue which should be out in the next jasm release :)

Will try to get the release out today
