### ISSUE TITLE
Option to continue without 3dmigoto installed

### ISSUE THREAD

**Issue by Foolishkun** [Jorixon/JASM#291]
**Is your feature request related to a problem? Please describe.**

I've been using XXMI Launcher and had to reinstall GIMI and such through the XXMI Launcher, which doesn't use the 3dmigoto.exe. When setting up your folders in JASM you have to select a folder with the 3dmigoto.exe, which I can not. So I currently have to keep 3dmigoto installed to get through this.
 
**Describe the solution you'd like**

Remove the requirement of 3dmigoto.exe entirely.
or
Checkbox for XXMI users that bypasses the requirement.

**Comment by Pyrageis** [comment]
still uses 3dmigoto just renamed, as a work around for now go to the folder there and make a SYMLINK named 3dmigoto.exe that links to whatever the games MI exe is

**Comment by Foolishkun** [comment]
> still uses 3dmigoto just renamed, as a work around for now go to the folder there and make a SYMLINK named 3dmigoto.exe that links to whatever the games MI exe is

Yeah their own fork of 3dmigoto IIRC. Seems to be packaged into the launcher and only called when launched.
Creating a properly named SYMLINK pointing to anything worked, thanks for the tip!

**Comment by Jorixon** [comment]
I think I changed the validation a while back. Should just give you a (yellow) warning if the 3dMigoto exe is missing but still allow you to select the folder.

Currently, the only requirement for both 3Dmigoto and mods folder is that the path is a valid file system path and that the folder exists.

I verified this now by creating empty folders and selecting them during startup, and everything seemed to work fine

**Comment by Foolishkun** [comment]
> I think I changed the validation a while back. Should just give you a (yellow) warning if the 3dMigoto exe is missing but still allow you to select the folder.
> 
> Currently, the only requirement for both 3Dmigoto and mods folder is that the path is a valid file system path and that the folder exists.
> 
> I verified this now by creating empty folders and selecting them during startup, and everything seemed to work fine

Aha my bad, I assumed it wouldn't work without it since the "save" was not clickable without setting the folder for the .exe
Thanks!
