### ISSUE TITLE
Cant find March 7th The Hunt

### ISSUE THREAD

**Issue by Deen7Master** [Jorixon/JASM#303]
Cant find March 7th The Hunt
![image (3)](https://github.com/user-attachments/assets/0c9ac92d-7174-4217-a801-dbaa0e3a0b84)
![image (4)](https://github.com/user-attachments/assets/e32a37e3-4123-4566-9bb8-52f8616a2cde)
i want to disable mod March 7th The Hunt but i cant found
i have 5 mod but it show only 3 mod

**Comment by Przyhol** [comment]
don't know if you found the solution already, but if not you can access march 7th hunt by clicking the select skin option in march 7th
![march](https://github.com/user-attachments/assets/113d8888-44ab-4a9b-a715-a822282a2307)

**Comment by Jorixon** [comment]
As Przyhol mentioned "March 7th The Hunt" is added as a sub skin. However, if you'd like for it to have its own skin folder you can toggle skins as character on the settings page under the folder section.
![image](https://github.com/user-attachments/assets/02224cae-5e33-4070-93ed-fecaaa1def7f)

Then you can rename the character skin in the character manager.

Closing this issue.
