### ISSUE TITLE
[BUG] "More than one character mod active" icon display incorrectly

### ISSUE THREAD

**Issue by Yashirow** [Jorixon/JASM#54]
Hi, there's a small bug with the `Move Mods to another skin` feature. I only got this issue with Ayaka (I think i know why, I'll explain right after) so i can't tell if it's the same with others characters.

I'm currently using the 4k Character pack by DiXiao but the Ayaka skin wasn't recognized as her skin in JASM (I think it's because the ini isn't named correctly: `AyakaFruhlingMod.ini`). So I used the `Move Mods to another skin` feature but there's still the small icon which indicate that there's more than one skin active at the time.

<details>
<summary>Images</summary>

![image](https://github.com/Jorixon/JASM/assets/100087778/a6fca1f0-261b-4a5f-a8eb-7425b0a5c699)
![image](https://github.com/Jorixon/JASM/assets/100087778/dea09c45-bf8f-42b0-a08a-0c374e66f370)
![image](https://github.com/Jorixon/JASM/assets/100087778/4143bad8-bb9b-4487-b709-b49d3f52b73a)

</details>

**Comment by Jorixon** [comment]
Nice catch 👍
Fix coming in the next release.
