### ISSUE TITLE
Preview image of mods and merge.ini hotkey editing

### ISSUE THREAD

**Issue by Jorixon** [Jorixon/JASM#7]
This might need a redesign of character mod page. Would be nice to be able to see a preview image and hot keys for mods

**Comment by Jorixon** [comment]
![AnotherPageMoreImages](https://github.com/Jorixon/JASM/assets/143650598/c14f04f7-9f6d-42c1-b3d1-68a3361a64d2)
![ExpandGridMods](https://github.com/Jorixon/JASM/assets/143650598/4b159464-7d7c-4385-805f-84dded7fadc1)
![ListDetailed](https://github.com/Jorixon/JASM/assets/143650598/710af819-34c9-4305-b65c-828aad6e2ea7)
![NewWindowStrat](https://github.com/Jorixon/JASM/assets/143650598/cb688b5a-28f1-4160-b0f7-d697484fd950)

**Comment by Jorixon** [comment]
2. 
 ![ExpandGridMods](https://github.com/Jorixon/JASM/assets/143650598/4b159464-7d7c-4385-805f-84dded7fadc1)

**Comment by Jorixon** [comment]
3. 
![ListDetailed](https://github.com/Jorixon/JASM/assets/143650598/710af819-34c9-4305-b65c-828aad6e2ea7)

**Comment by Jorixon** [comment]
4.
![NewWindowStrat](https://github.com/Jorixon/JASM/assets/143650598/cb688b5a-28f1-4160-b0f7-d697484fd950)

**Comment by muscularcandy67** [comment]
While previewing image and mod, one thing it could be added if you can, if you use layout 3 or 4 on "What to put here??" you could check if there is a url file linked in the mod folder and show the mod page

**Comment by Jorixon** [comment]
![image](https://github.com/Jorixon/JASM/assets/143650598/6227c308-d383-486f-9060-c756776c8e2b)
