### ISSUE TITLE
Windows App Runtime issue

### ISSUE THREAD

**Issue by ryanKinoti** [Jorixon/JASM#72]
Hi there, I just installed the latest windows app runtime on my PC and when i try to run JASM i am getting the error attached on the image below
![Screenshot 2023-10-23 102022](https://github.com/Jorixon/JASM/assets/98760177/b118a795-01c9-41f6-a701-a45beeacf479)

aside from the other installed Windows App Runtime versions (from 1.1 to 1.3) installed, i also added 1.4 as required and still getting the above error.
the version 1.4 I have is: 4000.1010.1349.0

**Comment by Jorixon** [comment]
Just to be completely sure, you download this one, right?
![image](https://github.com/Jorixon/JASM/assets/143650598/daab6689-a6c8-4da4-9c26-386aa3d7aa93)

If that is the case, then I'm sorry to say that I really don't know what causes this problem. So far, you're the second person that I know of that has had this problem...

I've tried looking into it with no luck.

Windows event logs might tell you something if you want to debug:
![image](https://github.com/Jorixon/JASM/assets/143650598/163e09d1-56e6-4bc7-aea7-b2fd3b51bb5b)

**Comment by ryanKinoti** [comment]
i did download the SDK from your screenshot.
i have opened the event viewer and its error is as shown in the image below

![Screenshot (309)](https://github.com/Jorixon/JASM/assets/98760177/49791596-b51b-4e7f-8fee-5504fb7d04f6)

**Comment by elementers** [comment]
I am receiving a similar error related to the Windows App Runtime.
![error1](https://github.com/Jorixon/JASM/assets/118868461/6a800d69-631b-4dcc-8677-11a42e0f27d5)
![error2](https://github.com/Jorixon/JASM/assets/118868461/743a5dca-8f83-49a7-892c-f29777fe936b)
I've downloaded the 1.4.2 SDK, forced a repair and have .net 7.0 and .net Core installed

**Comment by elementers** [comment]
I was able to fix this, but it required me to reinstall windows.

**Comment by gxg1175** [comment]
Hi developers, thank you so much for sharing your work for free. I'm in a similar situation, I was able to open it before, but now I open it and it doesn't get an error pop-up, I see the same error code in the Event Viewer.

**Comment by H3XDaemon** [comment]
My solution was to download the redistributable package, unzip it and install all the msix files in the \MSIX\win10-x64 directory.
![image](https://github.com/Jorixon/JASM/assets/42803553/89d6e180-2b93-4d7d-bfcd-4a4d977aa64f)

**Comment by Jorixon** [comment]
I've started adding a self-contained version of JASM to the releases. This version has all dependencies bundled with it. The app size is quite a bit bigger as a result.

Uninstalling WinAppSdk and trying the self-contained version could potentially work. See #171

You can find this version on the releases page
https://github.com/Jorixon/JASM/releases/latest

**Comment by RagingGhosts** [comment]
When I use the self-contained verison, it still asks me to install WinAppSDK. Is there a way to fix this?

**Comment by Jorixon** [comment]
Oh...

Let me do some more testing

**Comment by RagingGhosts** [comment]
Yes it works now. Thank You!

**Comment by Jorixon** [comment]
Closing this as I belive the self contained version fixes this issue.
