### ISSUE TITLE
Add a category for paimon skin mods

### ISSUE THREAD

**Issue by Yashirow** [Jorixon/JASM#9]
Right know I have all my paimon skin mods in the "others" folder but I can't really sort them more than that. I need to separate them to disable or enable only one. Adding a folder for paimon skin mods could solve this. Or a subfolder in the "others" folder.
Same thing for gliders mods I guess.

Thanks for the manager by the way !

**Comment by Jorixon** [comment]
I'm thinking of adding a bunch of major characters (E.g. Paimon and Furina) soonTM. Just trying to see if there is some way to automate it. I guess adding gliders as its own "character" could actually work out.

One of the many things I'd like to implement is a way for the user to be able to create custom characters inside the app.

**Comment by Yashirow** [comment]
Also maybe one folder for character with skin ? Like "Keqing Opulent", 'Ningguang Ochid", etc.. cause those ones count as different characters (different hashes).

Allowing the user to create custom characters folder is also a great idea I think.
